version: '3.8'
services:
  web:
    image: nginx:stable-alpine
    container_name: turkoglu_nginx
    ports:
      - "8085:80"
    volumes:
      # Nokta yerine bu değişkeni kullanıyoruz:
      - ${DOCKER_COMPOSE_DIR}:/usr/share/nginx/html:ro
    restart: always
